# escape=`
FROM microsoft/windowsservercore:10.0.14393.2430_fr-fr

# Copy dll for the display of standard out
COPY vcruntime140.dll C:\\Windows\\System32\\vcruntime140.dll

# download servicemonitor  ???
RUN powershell -Command `
    Add-WindowsFeature Web-Server; `
    Invoke-WebRequest -UseBasicParsing -Uri "https://dotnetbinaries.blob.core.windows.net/servicemonitor/2.0.1.3/ServiceMonitor.exe" -OutFile "C:\ServiceMonitor.exe"
	
# Download php 
RUN powershell -Command `	
	[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 ; `
	Invoke-WebRequest -Uri  https://windows.php.net/downloads/releases/php-7.2.10-nts-Win32-VC15-x64.zip  -OutFile php.zip
	
# create Php directory
RUN powershell -Command `
	mkdir C:\php_7.2
	
# Extract downloaded php
RUN powershell -Command `
	Add-Type -AssemblyName System.IO.Compression.FileSystem ; `
	[System.IO.Compression.ZipFile]::ExtractToDirectory('C:\php.zip', 'C:\php_7.2')
	
# Php Ini
RUN powershell -Command `
	cp C:\php_7.2\php.ini-development C:\php_7.2\php.ini

# Set env path for php 
RUN setx /m PATH %PATH%;c:\php_7.2

#RUN powershell -Command `
#	Import-module iisadministration
	
#RUN powershell -Command `	
#	DISM.EXE /enable-feature /online /featureName:IIS-CGI /all
	
	
EXPOSE 80

ENTRYPOINT ["C:\\ServiceMonitor.exe", "w3svc"]

